<%@ Page Title="more" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="more.aspx.cs" Inherits="test3.more" %>

<%@ Register assembly="DevExpress.Web.v18.1, Version=18.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web" tagprefix="dx" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
   <header><h1>Dodge</h1></header>
    <body>
        <div>
            
        


    <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server">
        <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
        <Items>
            <dx:ImageSliderItem ImageUrl="~/morephoto/2.jpg" Name="2">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/morephoto/5.jpg" Name="5">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/morephoto/3.jpg" Name="3">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/morephoto/4.jpg" Name="4">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/morephoto/1.jpg" Name="1">
            </dx:ImageSliderItem>
        </Items>
    </dx:ASPxImageSlider>
    


    <br />
    <br />
    
    </div>

    </body>
    

</asp:Content>